# Generated by Django 3.0.7 on 2023-01-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0002_userdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='login',
            name='role',
            field=models.CharField(choices=[('super_admin', 'super_admin'), ('main_admin', 'main_admin'), ('admin', 'admin'), ('sub_admin', 'sub_admin'), ('group_admin', 'group_admin'), ('under_group_admin', 'under_group_admin')], default='super_admin', max_length=50),
        ),
    ]
