# Generated by Django 3.0.7 on 2023-01-23 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0005_resident'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp_app.Login'),
            preserve_default=False,
        ),
    ]
