# Generated by Django 3.0.7 on 2023-01-23 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0006_resident_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='user_id',
        ),
        migrations.AddField(
            model_name='login',
            name='mobile_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upcoming_otp', models.CharField(max_length=50)),
                ('mobile_number', models.BigIntegerField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_app.Login')),
            ],
        ),
    ]
