# Generated by Django 3.0.7 on 2023-01-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_app', '0007_auto_20230123_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='mobile_number',
            field=models.BigIntegerField(blank=True, default='0000000000', null=True),
        ),
    ]
